# Database PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=magnum
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fipe_db
quarkus.hibernate-orm.database.generation=update

# RabbitMQ configuration
mp.messaging.incoming.brands.connector=smallrye-rabbitmq
mp.messaging.incoming.brands.queue.name=brands
mp.messaging.incoming.brands.exchange.name=brands
mp.messaging.incoming.brands.routing-key=brand.load
mp.messaging.incoming.brands.prefetch-count=10
mp.messaging.incoming.brands.concurrency=5
mp.messaging.incoming.brands.retry-attempts=5
mp.messaging.incoming.brands.retry-delay=2
mp.messaging.incoming.brands.failure-strategy=requeue

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Redis configuration
quarkus.redis.hosts=redis://localhost:6379
quarkus.cache.type=redis
quarkus.cache.redis.vehicles-cache.expire-after-write=1h
quarkus.cache.redis.brands-cache.expire-after-write=1h

# REST Client FIPE API
fipe-api/mp-rest/url=https://parallelum.com.br/fipe/api/v1

# Indexing shared-domain dependency
quarkus.index-dependency.shared-domain.group-id=br.com.magnumbank
quarkus.index-dependency.shared-domain.artifact-id=shared-domain

# JWT Configuration
mp.jwt.verify.publickey.location=jwt/publicKey.pem
mp.jwt.verify.issuer=https://magnumbank.com.br

# Swagger configuration
quarkus.swagger-ui.always-include=true
