#Logging
quarkus.log.level=INFO
#quarkus.log.category."br.com.magnumbank".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# Database PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=magnum
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fipe_db

# REST Client FIPE API
fipe-api/mp-rest/url=https://parallelum.com.br/fipe/api/v1
fipe-api/mp-rest/connectTimeout=5000
fipe-api/mp-rest/readTimeout=5000

# RabbitMQ configuration
mp.messaging.outgoing.brands-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.brands-out.content-type=application/json
mp.messaging.outgoing.brands-out.exchange.name=brands
mp.messaging.outgoing.brands-out.exchange.type=topic
mp.messaging.outgoing.brands-out.routing-key=brand.load

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Redis configuration
quarkus.redis.hosts=redis://localhost:6379
quarkus.cache.type=redis
# TTL de 1 hora por padrão para todos os caches, mas podemos ser específicos
quarkus.cache.redis.vehicles-cache.expire-after-write=1h
quarkus.cache.redis.brands-cache.expire-after-write=1h

# Swagger configuration
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.security-scheme=OIDC

# Indexing shared-domain dependency
quarkus.index-dependency.shared-domain.group-id=br.com.magnumbank
quarkus.index-dependency.shared-domain.artifact-id=shared-domain

# JWT Configuration
mp.jwt.verify.publickey.location=jwt/publicKey.pem
mp.jwt.verify.issuer=https://magnumbank.com.br
smallrye.jwt.sign.key.location=jwt/privateKey.pem
smallrye.jwt.new-token.issuer=https://magnumbank.com.br
smallrye.jwt.new-token.lifespan=1800
